name: Build Max External

on:
  push:
    branches:
      - master
      - develop
      - "release/*"
    tags:
      - "*.*.*"

  pull_request:
    branches:
      - master
      - develop
      - "release/*"

  workflow_dispatch:

jobs:
  build-external:
    name: Build Max External
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Max External
        run: |
          cd plugins/max-external/btrack\~/
          chmod +x ./build-max-external.sh
          ./build-max-external.sh

      - name: Zip up external
        run: |
          cd plugins/max-external/btrack~/output
          zip -r btrack~.zip btrack~.mxo

      - name: Upload Max External
        uses: actions/upload-artifact@v4
        with:
          name: btrack-max-external
          path: plugins/max-external/btrack~/output/btrack~.zip
